FROM debian
MAINTAINER David Bainbridge <dbainbri@ciena.com>

ENV DEBIAN_FRONTEND noninteractive

ENV MININET_REPO git://github.com/mininet/mininet
ENV MININET_INSTALLER ./mininet/util/install.sh
ENV INSTALLER_SWITCHES -fbinptvwyx

ENV CONTAINERNET_REPO git://github.com/mpeuster/containernet.git
ENV CONTAINERNET_INSTALLER ./containernet/util/install.sh

WORKDIR /tmp

# Update and install minimal.
RUN \
    apt-get update \
        --quiet \
    && apt-get install \
        --yes \
        --no-install-recommends \
        --no-install-suggests \
    autoconf \
    automake \
    ca-certificates \
    git \
    curl \
    libtool \
    net-tools \
    openssh-client \
    patch \
    vim \
    nano \
    apt-transport-https \
    ca-certificates \
    curl \
    iptables\
    sudo
RUN apt-get install \
        --yes \
        --no-install-recommends \
        --no-install-suggests \
    python-pip
#RUN easy_install python-pip
RUN pip install  setuptools  urllib3 pytest docker-py==1.7.1


#install docker
RUN apt-get install -y     lxc
RUN curl -sSL https://get.docker.com/ | sh
# Clone and install.
RUN git clone  $CONTAINERNET_REPO \

# A few changes to make the install script behave.
    #&& sed -e 's/sudo //g' \
    #	-e 's/~\//\//g' \
    #	-e 's/\(apt-get -y -q install\)/\1 --no-install-recommends --no-install-suggests/g' \
    #	-i $CONTAINERNET_INSTALLER \


# Install script expects to find this. Easier than patching that part of the script.
    && touch /.bashrc \

# Proceed with the install.
    && chmod +x $CONTAINERNET_INSTALLER \
    && ./$CONTAINERNET_INSTALLER -nfv \

# Clean up source.
    && rm -rf /tmp/mininet \
              /tmp/openflow \

# Clean up packages.
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*





# Create a start script to start OpenVSwitch
    
COPY docker-entry-point /docker-entry-point
RUN chmod 755 /docker-entry-point
VOLUME ["/data"]
WORKDIR /data

# Default command.
ENTRYPOINT ["/docker-entry-point"]
